return {
    effect = {
        -- Extra Bees.
        ["acidic"] = "extrabees.effect.acid.name",
        ["birthday"] = "extrabees.effect.birthday.name",
        ["creepers"] = "extrabees.effect.spawncreeper.name",
        ["darkness"] = "extrabees.effect.blindness.name",
        ["ectoplasm"] = "extrabees.effect.ectoplasm.name",
        ["fireworks"] = "extrabees.effect.fireworks.name",
        ["gravity"] = "extrabees.effect.gravity.name",
        ["growth"] = "extrabees.effect.bonemealsapling.name",
        ["hunger"] = "extrabees.effect.hunger.name",
        ["mushroom"] = "extrabees.effect.bonemealmushroom.name",
        ["ripening"] = "extrabees.effect.bonemealfruit.name",
        ["lightning"] = "extrabees.effect.lightning.name",
        ["meteor"] = "extrabees.effect.meteor.name",
        ["power"] = "extrabees.effect.power.name",
        ["skeletons"] = "extrabees.effect.spawnskeleton.name",
        ["slowness"] = "extrabees.effect.slow.name",
        ["teleport"] = "extrabees.effect.teleport.name",
        ["unstable"] = "extrabees.effect.radioactive.name",
        ["water"] = "extrabees.effect.water.name",
        ["wither"] = "extrabees.effect.wither.name",
        ["zombies"] = "extrabees.effect.spawnzombie.name",

        -- Forestry.
        ["aggress."] = "forestry.allele.effect.aggressive",
        ["aggressive"] = "forestry.allele.effect.aggressive",
        ["beatific"] = "forestry.allele.effect.beatific",
        ["creeper"] = "forestry.allele.effect.creeper",
        ["drunkard"] = "forestry.allele.effect.drunkard",
        ["explorer"] = "forestry.allele.effect.exploration",
        ["fertile"] = "forestry.allele.effect.fertile",
        ["festive"] = "forestry.allele.effect.festiveEaster",
        ["freezing"] = "forestry.allele.effect.glacial",
        ["heroic"] = "forestry.allele.effect.heroic",
        ["flammable"] = "forestry.allele.effect.ignition",
        ["poison"] = "forstry.allele.effect.miasmic",
        ["ends"] = "forestry.allele.effect.misanthrope",
        ["mycophilic"] = "forestry.allele.effect.mycophilic",
        ["none"] = "forestry.allele.effect.none",
        ["radioact."] = "forestry.allele.effect.radioactive",
        ["radioactive"] = "forestry.allele.effect.radioactive",
        ["reanimation"] = "forestry.allele.effect.reanimation",
        ["repulsion"] = "forestry.allele.effect.repulsion",
        ["resurrection"] = "forestry.allele.effect.resurrection",
        ["snow"] = "forestry.allele.effect.snowing",

        -- Gregtech.
        ["treetwister"] = "gregtech.effectTreetwister",
        ["machine booster"] = "gregtech.effectMachineBoost",

        -- Magic Bees.
        ["ablaze"] = "magicbees.effectAblaze",
        ["basalzy"] = "magicbees.effectTEBasalz",
        ["batty"] = "magicbees.effectBatty",
        ["blitzy"] = "magicbees.effectTEBlitzy",
        ["blizzy"] = "magicbees.effectTEBlizzy",
        ["bovine"] = "magicbees.effectBovine",
        ["brainy"] = "magicbees.effectBrainy",
        ["catty"] = "magicbees.effectCatty",
        ["cleansing"] = "magicbee.effectCurative",
        ["crumbling"] = "magicbees.effectCrumbling",
        ["dreaming"] = "magicbees.effectDreaming",
        ["empowering"] = "magicbees.effectNodeEmpower",
        ["ghastly"] = "magicbees.effectGhastly",
        ["howling"] = "magicbees.effectCanine",
        ["invsbl."] = "magicbees.effectInvisibility",
        ["invisible"] = "magicbees.effectInvisibility",
        ["magnification"] = "magicbees.effectNodeRepair",
        ["mana drain"] = "magicBees.effectManaDrainer",
        ["mining"] = "magicbees.effectDigSpeed",
        ["neighsayer"] = "magicbees.effectHorse",
        ["plucky"] = "magicbees.effectChicken",
        ["porcine"] = "magicbees.effectPorcine",
        ["purifying"] = "magicbees.effectNodePurifying",
        ["ravening"] = "magicbees.effectNodeRavening",
        ["recharging"] = "magicbees.effectVisRecharge",
        ["spidery"] = "magicbees.effectSpidery",
        ["spiritual"] = "magicbees.effectAMWisp",
        ["swiftness"] = "magicbees.effectMoveSpeed",
        ["tainting"] = "magicbes.effectNodeTainting",
        ["time warp"] = "magicbees.effectSlowSpeed",
        ["transmuting"] = "magicbees.effectTransmuting",
        ["vortex"] = "magicbees.effectManaDrainer",
        ["wispy"] = "magicbees.effectWispy",
        ["withering"] = "magicbees.effectWithering",
        ["wooly"] = "magicbees.effectSheep",
    },
    flowering = {
        ["slowest"] = 5,
        ["slower"] = 10,
        ["slow"] = 15,
        ["average"] = 20,
        ["fast"] = 25,
        ["faster"] = 30,
        ["fastest"] = 35,
        ["maximum"] = 99,
    },
    flowerProvider = {
        -- Computronics.
        ["sea"] = "computronics.flowers.sea",

        -- Extra Bees.
        ["books"] = "extrabees.flowers.book",
        ["dead bushes"] = "extrabees.flower.dead",
        ["fruit"] = "extrabees.flowers.fruit",
        ["leaves"] = "extrabees.flowers.leaves",
        ["lily pad"] = "extrabees.flowers.water",
        ["mystical"] = "extrabees.flowers.mystical",
        ["redstone"] = "extrabees.flowers.redstone",
        ["reeds"] = "extrabees.flowers.sugar",
        ["rocks"] = "extrabees.flowers.rock",
        ["saplings"] = "extrabees.flowers.sapling",
        ["wood"] = "extrabees.flowers.wood",

        -- Forestry.
        ["cacti"] = "flowersCacti",
        ["end"] = "flowersEnd",
        ["flowers"] = "flowersVanilla",
        ["gourds"] = "flowersGourd",
        ["jungle"] = "flowersJungle",
        ["mushroom"] = "flowersMushrooms",
        ["nether"] = "flowersNether",
        ["snow"] = "flowersSnow",
        ["wheat"] = "flowersWheat",

        -- Magic Bees.
        ["exotic flowers"] = "flowersArsMagica",
        ["mystical flowers"] = "flowersBotania",
        ["node"] = "flowersThaumcraftAuraNode",
        ["thaumic flowers"] = "flowersThaumcraft",
        -- ["books"] = "flowersBookshelf",  -- Same name as the one from Extra Bees?
    },
    lifespan = {
        ["shortest"] = 10,
        ["shorter"] = 20,
        ["short"] = 30,
        ["shortened"] = 35,
        ["normal"] = 40,
        ["elongated"] = 45,
        ["long"] = 50,
        ["longer"] = 60,
        ["longest"] = 70,
        ["eon"] = 600,
    },
    speed = {
        ["slowest"] = 0.3,
        ["slower"] = 0.6,
        ["slow"] = 0.8,
        ["normal"] = 1.0,
        ["fast"] = 1.2,
        ["faster"] = 1.4,
        ["fastest"] = 1.7,
        ["blinding"] = 2.0,
    },
    territory = {
        ["average"] = {9, 6, 9},
        ["large"] = {11, 8, 11},
        ["larger"] = {12, 13, 12},
        ["largest"] = {13, 15, 13},
    },
}
