return {
    effect = {
        -- Extra Bees.
        ["acidic"] = "extrabees.effect.acid.name",
        ["birthday"] = "extrabees.effect.birthday.name",
        ["creepers"] = "extrabees.effect.spawncreeper.name",
        ["darkness"] = "extrabees.effect.blindness.name",
        ["ectoplasm"] = "extrabees.effect.ectoplasm.name",
        ["fireworks"] = "extrabees.effect.fireworks.name",
        ["gravity"] = "extrabees.effect.gravity.name",
        ["growth"] = "extrabees.effect.bonemealsapling.name",
        ["hunger"] = "extrabees.effect.hunger.name",
        ["mushroom"] = "extrabees.effect.bonemealmushroom.name",
        ["ripening"] = "extrabees.effect.bonemealfruit.name",
        ["lightning"] = "extrabees.effect.lightning.name",
        ["meteor"] = "extrabees.effect.meteor.name",
        ["power"] = "extrabees.effect.power.name",
        ["skeletons"] = "extrabees.effect.spawnskeleton.name",
        ["slowness"] = "extrabees.effect.slow.name",
        ["teleport"] = "extrabees.effect.teleport.name",
        ["unstable"] = "extrabees.effect.radioactive.name",
        ["water"] = "extrabees.effect.water.name",
        ["wither"] = "extrabees.effect.wither.name",
        ["zombies"] = "extrabees.effect.spawnzombie.name",

        -- Forestry.
        ["aggress."] = "forestry.allele.effect.aggressive",
        ["aggressive"] = "forestry.allele.effect.aggressive",
        ["beatific"] = "forestry.allele.effect.beatific",
        ["creeper"] = "forestry.allele.effect.creeper",
        ["drunkard"] = "forestry.allele.effect.drunkard",
        ["explorer"] = "forestry.allele.effect.exploration",
        ["fertile"] = "forestry.allele.effect.fertile",
        ["festive"] = "forestry.allele.effect.festiveEaster",
        ["freezing"] = "forestry.allele.effect.glacial",
        ["heroic"] = "forestry.allele.effect.heroic",
        ["flammable"] = "forestry.allele.effect.ignition",
        ["poison"] = "forstry.allele.effect.miasmic",
        ["ends"] = "forestry.allele.effect.misanthrope",
        ["mycophilic"] = "forestry.allele.effect.mycophilic",
        ["none"] = "forestry.allele.effect.none",
        ["radioact."] = "forestry.allele.effect.radioactive",
        ["radioactive"] = "forestry.allele.effect.radioactive",
        ["reanimation"] = "forestry.allele.effect.reanimation",
        ["repulsion"] = "forestry.allele.effect.repulsion",
        ["resurrection"] = "forestry.allele.effect.resurrection",
        ["snow"] = "forestry.allele.effect.snowing",

        -- Gregtech.
        ["treetwister"] = "gregtech.effectTreetwister",
        ["machine booster"] = "gregtech.effectMachineBoost",

        -- Magic Bees.
        ["ablaze"] = "magicbees.effectAblaze",
        ["basalzy"] = "magicbees.effectTEBasalz",
        ["batty"] = "magicbees.effectBatty",
        ["blitzy"] = "magicbees.effectTEBlitzy",
        ["blizzy"] = "magicbees.effectTEBlizzy",
        ["bovine"] = "magicbees.effectBovine",
        ["brainy"] = "magicbees.effectBrainy",
        ["catty"] = "magicbees.effectCatty",
        ["cleansing"] = "magicbee.effectCurative",
        ["crumbling"] = "magicbees.effectCrumbling",
        ["dreaming"] = "magicbees.effectDreaming",
        ["empowering"] = "magicbees.effectNodeEmpower",
        ["ghastly"] = "magicbees.effectGhastly",
        ["howling"] = "magicbees.effectCanine",
        ["invsbl."] = "magicbees.effectInvisibility",
        ["invisible"] = "magicbees.effectInvisibility",
        ["magnification"] = "magicbees.effectNodeRepair",
        ["mana drain"] = "magicBees.effectManaDrainer",
        ["mining"] = "magicbees.effectDigSpeed",
        ["neighsayer"] = "magicbees.effectHorse",
        ["plucky"] = "magicbees.effectChicken",
        ["porcine"] = "magicbees.effectPorcine",
        ["purifying"] = "magicbees.effectNodePurifying",
        ["ravening"] = "magicbees.effectNodeRavening",
        ["recharging"] = "magicbees.effectVisRecharge",
        ["spidery"] = "magicbees.effectSpidery",
        ["spiritual"] = "magicbees.effectAMWisp",
        ["swiftness"] = "magicbees.effectMoveSpeed",
        ["tainting"] = "magicbes.effectNodeTainting",
        ["time warp"] = "magicbees.effectSlowSpeed",
        ["transmuting"] = "magicbees.effectTransmuting",
        ["vortex"] = "magicbees.effectManaDrainer",
        ["wispy"] = "magicbees.effectWispy",
        ["withering"] = "magicbees.effectWithering",
        ["wooly"] = "magicbees.effectSheep",
    },
    flowering = {
        ["slowest"] = 5,
        ["slower"] = 10,
        ["slow"] = 15,
        ["average"] = 20,
        ["fast"] = 25,
        ["faster"] = 30,
        ["fastest"] = 35,
        ["maximum"] = 99,
    },
    flowerProvider = {
        -- Computronics.
        ["sea"] = "computronics.flowers.sea",

        -- Extra Bees.
        ["dead bushes"] = "extrabees.flower.dead",
        ["fruit"] = "extrabees.flowers.fruit",
        ["leaves"] = "extrabees.flowers.leaves",
        ["lily pad"] = "extrabees.flowers.water",
        ["mystical"] = "extrabees.flowers.mystical",
        ["redstone"] = "extrabees.flowers.redstone",
        ["reeds"] = "extrabees.flowers.sugar",
        ["rocks"] = "extrabees.flowers.rock",
        ["saplings"] = "extrabees.flowers.sapling",
        ["wood"] = "extrabees.flowers.wood",

        -- Forestry.
        ["cacti"] = "flowersCacti",
        ["end"] = "flowersEnd",
        ["flowers"] = "flowersVanilla",
        ["gourds"] = "flowersGourd",
        ["jungle"] = "flowersJungle",
        ["mushroom"] = "flowersMushrooms",
        ["nether"] = "flowersNether",
        ["snow"] = "flowersSnow",
        ["wheat"] = "flowersWheat",

        -- Magic Bees.
        ["exotic flowers"] = "flowersArsMagica",
        ["mystical flowers"] = "flowersBotania",
        ["node"] = "flowersThaumcraftAuraNode",
        ["thaumic flowers"] = "flowersThaumcraft",

        -- Multiples.
        ["books"] = {
            "extrabees.flowers.book",
            "flowersBookshelf",
        }
    },
    lifespan = {
        ["shortest"] = 10,
        ["shorter"] = 20,
        ["short"] = 30,
        ["shortened"] = 35,
        ["normal"] = 40,
        ["elongated"] = 45,
        ["long"] = 50,
        ["longer"] = 60,
        ["longest"] = 70,
        ["eon"] = 600,
    },
    species = {
        ["abandoned"] = "magicbees.speciesAbandoned",
        ["abnormal"] = "extrabees.species.unusual",
        ["absolute"] = "extrabees.species.freezing",
        ["abyssal"] = "extrabees.species.abyss",
        ["acidic"] = "extrabees.species.acidic",
        ["aer"] = "magicbees.speciesTCAir",
        ["agrarian"] = "forestry.speciesAgrarian",
        ["air"] = "gregtech.bee.speciesAir",
        ["alfheim"] = "magicbees.speciesBotAlfheim",
        ["aluminium"] = "gregtech.bee.speciesAluminium",
        ["aluminum"] = "magicbees.speciesAluminum",
        ["amber"] = {
            "extrabees.species.orange",
            "gregtech.bee.speciesAmber",
        },
        ["americium"] = "gregtech.bee.speciesAmericium",
        ["ancient"] = "extrabees.species.ancient",
        ["apatine"] = "magicbees.speciesApatite",
        ["apatite"] = "gregtech.bee.speciesApatite",
        ["aqua"] = "magicbees.speciesTCWater",
        ["arcane"] = "magicbees.speciesArcane",
        ["arcaneshards"] = "gregtech.bee.speciesArcaneshards",
        ["ardite"] = "magicbees.speciesArdite",
        ["argentum"] = "magicbees.speciesSilver",
        ["argon"] = "gregtech.bee.speciesArgon",
        ["arid"] = "extrabees.species.arid",
        ["arsenic"] = "gregtech.bee.speciesArsenic",
        ["ash"] = "gregtech.bee.speciesAsh",
        ["ashen"] = "extrabees.species.lightgray",
        ["astral Silver"] = "gregtech.bee.speciesAstralsilver",
        ["attuned"] = "magicbees.speciesAttuned",
        ["auric"] = "magicbees.speciesGold",
        ["austere"] = "forestry.speciesAustere",
        ["avenging"] = "forestry.speciesAvenging",
        ["aware"] = "magicbees.speciesAware",
        ["azure"] = "extrabees.species.lightblue",
        ["barnarda"] = "gregtech.bee.speciesBarnarda",
        ["barnardaC"] = "gregtech.bee.speciesBarnardac",
        ["barnardaE"] = "gregtech.bee.speciesBarnardae",
        ["barnardaF"] = "gregtech.bee.speciesBarnardaf",
        ["barren"] = "extrabees.species.barren",
        ["batty"] = "magicbees.speciesTCBatty",
        ["bedrockium"] = "gregtech.bee.speciesBedrockium",
        ["beefy"] = "magicbees.speciesTCBeef",
        ["big bad"] = "magicbees.speciesBigBad",
        ["black"] = "gendustry.bee.black",
        ["black plutonium"] = "gregtech.bee.speciesBlackplutonium",
        ["bleached"] = "extrabees.species.white",
        ["blooming"] = "extrabees.species.blooming",
        ["blossom"] = "magicbees.speciesBotBlossom",
        ["blue"] = "gendustry.bee.blue",
        ["blutonium"] = "extrabees.species.blutonium",
        ["boggy"] = "forestry.speciesBoggy",
        ["botanic"] = "magicbees.speciesBotBotanic",
        ["bovine"] = "extrabees.species.milk",
        ["brainy"] = "magicbees.speciesTCBrainy",
        ["bronzed"] = "magicbees.speciesTEBronze",
        ["brown"] = "gendustry.bee.brown",
        ["caelestis"] = "gregtech.bee.speciesCaelestis",
        ["caffeinated"] = "extrabees.species.coffee",
        ["callisto"] = "gregtech.bee.speciesCallisto",
        ["callisto ice"] = "gregtech.bee.speciesCallistoice",
        ["catty"] = "magicbees.speciesCatty",
        ["caustic"] = "extrabees.species.caustic",
        ["celebratory"] = "extrabees.species.celebratory",
        ["centauri"] = "gregtech.bee.speciesCentauri",
        ["ceres"] = "gregtech.bee.speciesCeres",
        ["certus"] = {
            "gregtech.bee.speciesCertus",
            "magicbees.speciesCertus",
        },
        ["chad"] = "extrabees.species.chad",
        ["chaos"] = "gregtech.bee.speciesChaos",
        ["chaotic"] = "magicbees.speciesTCChaos",
        ["charmed"] = "magicbees.speciesCharmed",
        ["chrome"] = "gregtech.bee.speciesChrome",
        ["clay"] = "gregtech.bee.speciesClay",
        ["coal"] = "gregtech.bee.speciesCoal",
        ["cobalt"] = "magicbees.speciesCobalt",
        ["common"] = "forestry.speciesCommon",
        ["conductive iron"] = "gregtech.bee.speciesConductiveiron",
        ["coolant"] = "gregtech.bee.speciesCoolant",
        ["copper"] = "gregtech.bee.speciesCopper",
        ["corroded"] = "extrabees.species.copper",
        ["corrosive"] = "extrabees.species.corrosive",
        ["cosmic neutronium"] = "gregtech.bee.speciesCosmicneutronium",
        ["creepy"] = "extrabees.species.creeper",
        ["crumbling"] = "magicbees.speciesCrumbling",
        ["cryolite"] = "gregtech.bee.speciesCryolite",
        ["cryotheum"] = "gregtech.bee.speciesCryotheum",
        ["cultivated"] = "forestry.speciesCultivated",
        ["cuprum"] = "magicbees.speciesCopper",
        ["cyan"] = "gendustry.bee.cyan",
        ["cyanite"] = "extrabees.species.cyanite",
        ["d-o-b"] = "gregtech.bee.speciesDob",
        ["damp"] = "extrabees.species.swamp",
        ["dark steel"] = "gregtech.bee.speciesDarksteel",
        ["darkened"] = "extrabees.species.darkened",
        ["decaying"] = "extrabees.species.rotten",
        ["decomposing"] = "extrabees.species.decomposing",
        ["deimos"] = "gregtech.bee.speciesDeimos",
        ["demonic"] = "forestry.speciesDemonic",
        ["derpious"] = "gendustry.bee.derpious",
        ["desh"] = "gregtech.bee.speciesDesh",
        ["desolate"] = "extrabees.species.desolate",
        ["diamandi"] = "magicbees.speciesDiamond",
        ["diamond"] = {
            "extrabees.species.diamond",
            "gregtech.bee.speciesDiamond",
        },
        ["diligent"] = "forestry.speciesDiligent",
        ["distilled"] = "extrabees.species.distilled",
        ["doctoral"] = "magicbees.speciesDoctoral",
        ["draconic"] = "magicbees.speciesDraconic",
        ["dragon blood"] = "gtpp.bee.speciesDragon Blood",
        ["dragon essence"] = "gregtech.bee.speciesDragonessence",
        ["drake"] = "gregtech.bee.speciesDrake",
        ["dreaming"] = "magicbees.speciesBotDreaming",
        ["earth"] = "gregtech.bee.speciesEarth",
        ["earthen"] = "magicbees.speciesEarthen",
        ["ebony"] = "extrabees.species.black",
        ["ecstatic"] = "extrabees.species.ecstatic",
        ["ectoplasma"] = "gregtech.bee.speciesEctoplasma",
        ["edenic"] = "forestry.speciesEdenic",
        ["elastic"] = "extrabees.species.latex",
        ["eldritch"] = "magicbees.speciesEldritch",
        ["electrical steel"] = "gregtech.bee.speciesElectricalsteel",
        ["electrotine"] = "gregtech.bee.speciesElectrotine",
        ["electrum"] = "magicbees.speciesTEElectrum",
        ["embittered"] = "extrabees.species.basalt",
        ["emerald"] = {
            "extrabees.species.emerald",
            "gregtech.bee.speciesEmerald",
        },
        ["empowering"] = "magicbees.speciesTCEmpowering",
        ["enceladus"] = "gregtech.bee.speciesEnceladus",
        ["enchanted"] = "magicbees.speciesEnchanted",
        ["end dust"] = "gregtech.bee.speciesEnddust",
        ["ender"] = "forestry.speciesEnded",
        ["enderium"] = "gregtech.bee.speciesEnderium",
        ["endermanhead"] = "gregtech.bee.speciesEndermanhead",
        ["endium"] = "gregtech.bee.speciesEndium",
        ["endshard"] = "gregtech.bee.speciesEndshard",
        ["energetic"] = "extrabees.species.energetic",
        ["energetic alloy"] = "gregtech.bee.speciesEnergeticalloy",
        ["energy"] = "gregtech.bee.speciesEnergy",
        ["esmeraldi"] = "magicbees.speciesEmerald",
        ["esoteric"] = "magicbees.speciesEsoteric",
        ["essentia"] = {
            "gregtech.bee.speciesEssentia",
            "magicbees.speciesTCEssentia",
        },
        ["ethereal"] = "magicbees.speciesEthereal",
        ["europa"] = "gregtech.bee.speciesEuropa",
        ["excited"] = "extrabees.species.excited",
        ["exotic"] = "forestry.speciesExotic",
        ["explosive"] = "gregtech.bee.speciesExplosive",
        ["farmed"] = "extrabees.species.farm",
        ["farmerly"] = "forestry.speciesFarmerly",
        ["fermented"] = "extrabees.species.alcohol",
        ["ferrous"] = "magicbees.speciesIron",
        ["fertilizer"] = "gregtech.bee.speciesFertilizer",
        ["fiendish"] = "forestry.speciesFiendish",
        ["fire"] = "gregtech.bee.speciesFire",
        ["fireessence"] = "gregtech.bee.speciesFireessence",
        ["firestone"] = "gregtech.bee.speciesFirestone",
        ["firey"] = "magicbees.speciesFirey",
        ["floral"] = "magicbees.speciesBotFloral",
        ["fluix"] = {
            "gregtech.bee.speciesFluix",
            "magicbees.speciesFluix",
        },
        ["fluorine"] = "gregtech.bee.speciesFluorine",
        ["flux"] = "magicbees.speciesTCFlux",
        ["force"] = "gtpp.bee.speciesForce",
        ["forest"] = "forestry.speciesForest",
        ["forlorn"] = "magicbees.speciesForlorn",
        ["fossilised"] = "extrabees.species.coal",
        ["frigid"] = "extrabees.species.artic",
        ["frugal"] = "forestry.speciesFrugal",
        ["fruity"] = "extrabees.species.fruit",
        ["fuchsia"] = "extrabees.species.magenta",
        ["fungal"] = "extrabees.species.fungal",
        ["furious"] = "extrabees.species.tempered",
        ["galvanized"] = "extrabees.species.zinc",
        ["ganymed"] = "gregtech.bee.speciesGanymede",
        ["ghastly"] = "magicbees.speciesGhastly",
        ["glacial"] = "forestry.speciesGlacial",
        ["glittering"] = "extrabees.species.gold",
        ["glowering"] = "extrabees.species.glowstone",
        ["glowstone"] = "gregtech.bee.speciesGlowstone",
        ["glutinous"] = "extrabees.species.glutinous",
        ["gnawing"] = "extrabees.species.gnawing",
        ["gold"] = "gregtech.bee.speciesGold",
        ["gray"] = "gendustry.bee.gray",
        ["green"] = "gendustry.bee.green",
        ["growing"] = "extrabees.species.growing",
        ["hateful"] = "magicbees.speciesHateful",
        ["haume"] = "gregtech.bee.speciesHaumea",
        ["hazardous"] = "extrabees.species.hazardous",
        ["helium"] = "gregtech.bee.speciesHelium",
        ["hermitic"] = "forestry.speciesHermitic",
        ["heroic"] = "forestry.speciesHeroic",
        ["hydra"] = "gregtech.bee.speciesHydra",
        ["hydrogen"] = "gregtech.bee.speciesHydrogen",
        ["icy"] = "forestry.speciesIcy",
        ["ignis"] = "magicbees.speciesTCFire",
        ["imperial"] = "forestry.speciesImperial",
        ["indigo"] = "extrabees.species.purple",
        ["indium"] = "gregtech.bee.speciesIndium",
        ["industrious"] = "forestry.speciesIndustrious",
        ["infectious"] = "extrabees.species.infectious",
        ["infernal"] = "magicbees.speciesInfernal",
        ["infinity"] = "gregtech.bee.speciesInfinity",
        ["infinity catalyst"] = "gregtech.bee.speciesInfinitycatalyst",
        ["infused gold"] = "gregtech.bee.speciesInfusedgold",
        ["invar"] = "magicbees.speciesTEInvar",
        ["invisible"] = "magicbees.speciesInvisible",
        ["io"] = "gregtech.bee.speciesIo",
        ["iridium"] = "gregtech.bee.speciesIridium",
        ["iron"] = "gregtech.bee.speciesIron",
        ["jaded"] = "extrabees.species.jaded",
        ["jaegermeister"] = "gregtech.bee.speciesJaegermeister",
        ["jupiter"] = "gregtech.bee.speciesJupiter",
        ["kevlar"] = "gregtech.bee.speciesKevlar",
        ["krypton"] = "gregtech.bee.speciesKrypton",
        ["lapis"] = {
            "extrabees.species.lapis",
            "gregtech.bee.speciesLapis",
        },
        ["lapotron"] = "gregtech.bee.speciesLapotron",
        ["lavender"] = "extrabees.species.pink",
        ["lead"] = "gregtech.bee.speciesLead",
        ["leaden"] = "extrabees.species.lead",
        ["ledox"] = "gregtech.bee.speciesLedox",
        ["leporine"] = "forestry.speciesLeporine",
        ["lich"] = "gregtech.bee.speciesLich",
        ["light blue"] = "gendustry.bee.lightblue",
        ["light gray"] = "gendustry.bee.silver",
        ["lime"] = {
            "extrabees.species.limegreen",
            "gendustry.bee.lime",
        },
        ["lithium"] = "gregtech.bee.speciesLithium",
        ["lordly"] = "magicbees.speciesLordly",
        ["lustered"] = "extrabees.species.nickel",
        ["lutetium"] = "gregtech.bee.speciesLutetium",
        ["magenta"] = "gendustry.bee.magenta",
        ["majestic"] = "forestry.speciesMajestic",
        ["makeMake"] = "gregtech.bee.speciesMakemake",
        ["malicious"] = "extrabees.species.malicious",
        ["manganese"] = "gregtech.bee.speciesManganese",
        ["manyullyn"] = "magicbees.speciesManyullyn",
        ["maroon"] = "extrabees.species.red",
        ["mars"] = "gregtech.bee.speciesMars",
        ["marshy"] = "forestry.speciesMarshy",
        ["meadows"] = "forestry.speciesMeadows",
        ["mercury"] = "gregtech.bee.speciesMercury",
        ["merry"] = "forestry.speciesMerry",
        ["meteoric iron"] = "gregtech.bee.speciesMeteoriciron",
        ["mica"] = "gregtech.bee.speciesMica",
        ["miranda"] = "gregtech.bee.speciesMiranda",
        ["miry"] = "forestry.speciesMiry",
        ["mithril"] = "gregtech.bee.speciesMithril",
        ["modest"] = "forestry.speciesModest",
        ["monastic"] = "forestry.speciesMonastic",
        ["moon"] = "gregtech.bee.speciesMoon",
        ["mutable"] = "magicbees.speciesMutable",
        ["mysterious"] = "magicbees.speciesMysterious",
        ["mysterious crystal"] = "gregtech.bee.speciesMysteriouscrystal",
        ["mystical"] = {
            "extrabees.species.mystical",
            "magicbees.speciesMystical",
        },
        ["mytryl"] = "gregtech.bee.speciesMytryl",
        ["naga"] = "gregtech.bee.speciesNaga",
        ["nameless"] = "magicbees.speciesNameless",
        ["naquadah"] = "gregtech.bee.speciesNaquadah",
        ["naquadria"] = "gregtech.bee.speciesNaquadria",
        ["natural"] = "extrabees.species.green",
        ["neighsayer"] = "magicbees.speciesHorse",
        ["neon"] = "gregtech.bee.speciesNeon",
        ["neptune"] = "gregtech.bee.speciesNeptune",
        ["nethershard"] = "gregtech.bee.speciesNethershard",
        ["neutronium"] = "gregtech.bee.speciesNeutronium",
        ["nexus"] = "magicbees.speciesTCNexus",
        ["nickel"] = {
            "gregtech.bee.speciesNickel",
            "magicbees.speciesTENickel",
        },
        ["nitrogen"] = "gregtech.bee.speciesNitrogen",
        ["noble"] = "forestry.speciesNoble",
        ["nuclear"] = "extrabees.species.nuclear",
        ["oberon"] = "gregtech.bee.speciesOberon",
        ["oblivion"] = "magicbees.speciesOblivion",
        ["ocean"] = "extrabees.species.ocean",
        ["oil"] = "gregtech.bee.speciesOil",
        ["oily"] = "extrabees.species.oil",
        ["olivine"] = "gregtech.bee.speciesOlivine",
        ["orange"] = "gendustry.bee.orange",
        ["order"] = "gregtech.bee.speciesOrder",
        ["ordered"] = "magicbees.speciesTCOrder",
        ["oriharukon"] = "gregtech.bee.speciesOriharukon",
        ["osmium"] = "gregtech.bee.speciesOsmium",
        ["oxygen"] = "gregtech.bee.speciesOxygen",
        ["peat"] = "gregtech.bee.speciesPeat",
        ["phantasmal"] = "forestry.speciesPhantasmal",
        ["phobos"] = "gregtech.bee.speciesPhobos",
        ["phosphorus"] = "gregtech.bee.speciesPhosphorus",
        ["pink"] = "gendustry.bee.pink",
        ["platinum"] = {
            "gregtech.bee.speciesPlatinum",
            "magicbees.speciesTEPlatinum",
        },
        ["plumbum"] = "magicbees.speciesLead",
        ["pluto"] = "gregtech.bee.speciesPluto",
        ["plutonium"] = "gregtech.bee.speciesPlutonium",
        ["porcine"] = "magicbees.speciesTCPork",
        ["poultry"] = "magicbees.speciesTCChicken",
        ["prehistoric"] = "extrabees.species.prehistoric",
        ["primeval"] = "extrabees.species.primeval",
        ["proteus"] = "gregtech.bee.speciesProteus",
        ["prussian"] = "extrabees.species.blue",
        ["pulsating Iron"] = "gregtech.bee.speciesPulsatingiron",
        ["pupil"] = "magicbees.speciesPupil",
        ["pure"] = "magicbees.speciesTCPure",
        ["purple"] = "gendustry.bee.purple",
        ["pyrotheum"] = "gregtech.bee.speciesPyrotheum",
        ["quantium"] = "gregtech.bee.speciesQuantium",
        ["quantum"] = "extrabees.species.quantum",
        ["quicksilver"] = "gregtech.bee.speciesQuicksilver",
        ["ravening"] = "magicbees.speciesTCHungry",
        ["red"] = "gendustry.bee.red",
        ["red Alloy"] = "gregtech.bee.speciesRedalloy",
        ["red garnet"] = "gregtech.bee.speciesRedgarnet",
        ["redstone"] = "gregtech.bee.speciesRedstone",
        ["redstone alloy"] = "gregtech.bee.speciesRedstonealloy",
        ["refined"] = "extrabees.species.fuel",
        ["rejuvenating"] = "magicbees.speciesTCRejuvenating",
        ["relic"] = "extrabees.species.relic",
        ["resilient"] = "extrabees.species.mineral",
        ["resinous"] = "extrabees.species.resin",
        ["ripening"] = "extrabees.species.ripening",
        ["river"] = "extrabees.species.river",
        ["robust"] = "extrabees.species.granite",
        ["rocky"] = "extrabees.species.rock",
        ["rooted"] = "magicbees.speciesBotRooted",
        ["ruby"] = {
            "extrabees.species.ruby",
            "gregtech.bee.speciesRuby",
        },
        ["rune"] = "gregtech.bee.speciesRune",
        ["rural"] = "forestry.speciesRural",
        ["rusty"] = "extrabees.species.iron",
        ["saffron"] = "extrabees.species.yellow",
        ["salis mundus"] = "gregtech.bee.speciesSalismundus",
        ["salt"] = "gregtech.bee.speciesSalty",
        ["sandwich"] = "gregtech.bee.speciesSandwich",
        ["sapphire"] = {
            "extrabees.species.sapphire",
            "gregtech.bee.speciesSapphire",
        },
        ["saturn"] = "gregtech.bee.speciesSaturn",
        ["savant"] = "magicbees.speciesSavant",
        ["scholarly"] = "magicbees.speciesScholarly",
        ["scummy"] = "computronics.speciesScummy",
        ["seaweed"] = "gregtech.bee.speciesSeaweed",
        ["secluded"] = "forestry.speciesSecluded",
        ["sepia"] = "extrabees.species.brown",
        ["shadow metal"] = "gregtech.bee.speciesShadowmetal",
        ["shadowed"] = "extrabees.species.shadow",
        ["sheepish"] = "magicbees.speciesSheepish",
        ["shining"] = "extrabees.species.silver",
        ["silicon"] = "magicbees.speciesSilicon",
        ["silver"] = "gregtech.bee.speciesSilver",
        ["silverfish"] = "gregtech.bee.speciesSilverfish",
        ["sinister"] = "forestry.speciesSinister",
        ["skeletal"] = "extrabees.species.bone",
        ["skulking"] = "magicbees.speciesSkulking",
        ["skystone"] = "magicbees.speciesAESkystone",
        ["slate"] = "extrabees.species.gray",
        ["slimeball"] = "gregtech.bee.speciesSlimeball",
        ["smouldering"] = "magicbees.speciesSmouldering",
        ["snowqueen"] = "gregtech.bee.speciesSnowqueen",
        ["sodden"] = "extrabees.species.boggy",
        ["solum"] = "magicbees.speciesTCEarth",
        ["somnolent"] = "magicbees.speciesBotSomnolent",
        ["sorcerous"] = "magicbees.speciesSorcerous",
        ["soul"] = "magicbees.speciesSoul",
        ["space"] = "gregtech.bee.speciesSpace",
        ["spatial"] = "extrabees.species.spatial",
        ["spectral"] = "forestry.speciesSpectral",
        ["spidery"] = "magicbees.speciesSpidery",
        ["spirit"] = "magicbees.speciesSpirit",
        ["spiteful"] = "magicbees.speciesSpiteful",
        ["stained"] = "extrabees.species.ink",
        ["stainless steel"] = "gregtech.bee.speciesStainlesssteel",
        ["stannum"] = "magicbees.speciesTin",
        ["stardust"] = "gregtech.bee.speciesStardust",
        ["steadfast"] = "forestry.speciesSteadfast",
        ["steel"] = "gregtech.bee.speciesSteel",
        ["sticky"] = "extrabees.species.sticky",
        ["stickyresin"] = "gregtech.bee.speciesStickyresin",
        ["sugary"] = "extrabees.species.sugar",
        ["sulfur"] = "gregtech.bee.speciesSulfur",
        ["sunnarium"] = "gregtech.bee.speciesSunnarium",
        ["supernatural"] = "magicbees.speciesSupernatural",
        ["sweetened"] = "extrabees.species.sweet",
        ["tceti"] = "gregtech.bee.speciesTceti",
        ["tcetie"] = "gregtech.bee.speciesTcetie",
        ["tainted"] = "gregtech.bee.speciesTainted",
        ["tarnished"] = "extrabees.species.tin",
        ["tarry"] = "extrabees.species.creosote",
        ["tea"] = "gregtech.bee.speciesTea",
        ["thaumic shards"] = "gregtech.bee.speciesThaumiumshard",
        ["thauminite"] = "gregtech.bee.speciesThauminite",
        ["thaumium dust"] = "gregtech.bee.speciesThaumiumdust",
        ["thorium"] = "gregtech.bee.speciesThorium",
        ["thriving"] = "extrabees.species.thriving",
        ["timely"] = "magicbees.speciesTimely",
        ["tin"] = "gregtech.bee.speciesTin",
        ["tipsy"] = "forestry.speciesTipsy",
        ["titan"] = "gregtech.bee.speciesTitan",
        ["titanium"] = "gregtech.bee.speciesTitanium",
        ["tolerant"] = "extrabees.species.stone",
        ["transmuting"] = "magicbees.speciesTransmuting",
        ["tricky"] = "forestry.speciesTricky",
        ["trinium"] = "gregtech.bee.speciesTrinium",
        ["triton"] = "gregtech.bee.speciesTriton",
        ["tropical"] = "forestry.speciesTropical",
        ["tungsten"] = "gregtech.bee.speciesTungsten",
        ["turquoise"] = "extrabees.species.cyan",
        ["unknownwater"] = "gregtech.bee.speciesUnknownwater",
        ["unstable"] = {
            "extrabees.species.unstable",
            "gregtech.bee.speciesDivided",
        },
        ["unusual"] = "magicbees.speciesUnusual",
        ["unweary"] = "forestry.speciesUnweary",
        ["ur ghast"] = "gregtech.bee.speciesUrghast",
        ["uranium"] = "gregtech.bee.speciesUranium",
        ["uranus"] = "gregtech.bee.speciesUranus",
        ["valiant"] = "forestry.speciesValiant",
        ["valuable"] = "extrabees.species.platinum",
        ["vazbee"] = "magicbees.speciesBotVazbee",
        ["vega"] = "gregtech.bee.speciesVega",
        ["vegab"] = "gregtech.bee.speciesVegab",
        ["vengeful"] = "forestry.speciesVengeful",
        ["venus"] = "gregtech.bee.speciesVenus",
        ["vibrant alloy"] = "gregtech.bee.speciesVibrantalloy",
        ["vindictive"] = "forestry.speciesVindictive",
        ["virulent"] = "extrabees.species.virulent",
        ["vis"] = "magicbees.speciesTCVis",
        ["viscous"] = "extrabees.species.viscous",
        ["void"] = "magicbees.speciesTCVoid",
        ["volcanic"] = "extrabees.species.volcanic",
        ["walrus"] = "gregtech.bee.speciesWalrus",
        ["water"] = {
            "extrabees.species.water",
            "gregtech.bee.speciesWater",
        },
        ["watery"] = "magicbees.speciesWatery",
        ["white"] = "gendustry.bee.white",
        ["windy"] = "magicbees.speciesWindy",
        ["wintry"] = "forestry.speciesWintry",
        ["wispy"] = "magicbees.speciesTCWispy",
        ["wither"] = "gregtech.bee.speciesSparkeling",
        ["withering"] = "magicbees.speciesWithering",
        ["xenon"] = "gregtech.bee.speciesXenon",
        ["yellorium"] = "extrabees.species.yellorium",
        ["yellow"] = "gendustry.bee.yellow",
        ["yellow garnet"] = "gregtech.bee.speciesYellowgarnet",
        ["zinc"] = "gregtech.bee.speciesZinc",
        ["acentauri"] = "gregtech.bee.speciesAcentauri",
    },
    speed = {
        ["slowest"] = 0.3,
        ["slower"] = 0.6,
        ["slow"] = 0.8,
        ["normal"] = 1.0,
        ["fast"] = 1.2,
        ["faster"] = 1.4,
        ["fastest"] = 1.7,
        ["blinding"] = 2.0,
    },
    territory = {
        ["average"] = {9, 6, 9},
        ["large"] = {11, 8, 11},
        ["larger"] = {12, 13, 12},
        ["largest"] = {13, 15, 13},
    },
}
